React Calculator Project - Milestone 5 finished
Flakster/Math-magicians-calculator pull request #6
Opened 2021-02-24 14:47 UTC by Flakster

## This PR includes

* Transformation of  App component from a function to a class
* Addition of handleClick function to ButtonPanel component
* Attachment of the handleClick function to the onClick event on Button component
* Addition of the logic of the calculations

2021-02-24 18:34 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] check below 👇 

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-24 18:34 UTC, Spayco commented on src/components/App.js
> +  }
- [ ] `handleClick` should be implemented inside the constructor

2021-02-24 18:34 UTC, Spayco commented on src/components/ButtonPanel.js
>    return (
* [ ] ButtonPanel should have `handleClick` function implemented ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone5/panel/implementHandleClick.png))

```javascript
handleClick = (buttonName) => {
  this.props.clickHandler(buttonName);
};
```

2021-02-24 18:34 UTC, Spayco commented on src/components/ButtonPanel.js
>        </div>
- [ ] passe `handleClick` as `clickHandler` props to each `Button` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone5/panel/passToButton.png))

2021-02-24 21:56 UTC, Flakster commented
# This new submission includes
* Bind the handleClick function in the App class Constructor
* clickHandler function,  which takes buttonName as an argument was implemented
* handleClick function is passed as a property to each button

2021-02-25 01:12 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 

Great job  @Flakster, and thanks for making the required changes :hammer: :wrench:.

Now you can merge, your project is approved :checkered_flag: 

## Happy Coding :tophat:

2021-02-25 01:32 UTC, merged